version: '2.1'
services:
  mongod:
    restart: always
    image: mongo
    ports:
     - "127.0.0.1:${MONGO_PORT:-27017}:27017"
    volumes:
     - ./run/mongo:/data/db
    group_add:
     - users
  gunpowder:
    restart: always
    depends_on:
     - mongod
    build: .
    ports:
     - 8080:8080
     - "${MC_PORT:-25565}:25565"
     - "${MC_PORT:-25565}:25565/udp"
    volumes:
     - ./run/gunpowder:/work
    group_add:
     - users