version: '2'
services:
  mongod:
    image: mongo
    volumes:
     - ./db:/data/db
  gunpowder:
    depends_on:
       - mongod
    build: .
    ports:
     - "8080:8080"
     - "25566:25565"
    volumes:
     - ./work:/workdir